config/routes.rb
Rails.application.routes.draw do
  
  get 'tasks/all'

  root 'static#home'
  get 'signup'  => 'users#new'
  get 'login'   => 'sessions#new'
  post 'login'  => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  get 'my_tasks' => 'users#tasks'
  get 'au_handle' => 'static#available_users'
  get 'avalable_users/:date' => 'users#get_available_users'

  resources :tasks

  resources :users do
    member do
      get :roaster
      post :update_roaster
      get :holiday
      post :create_holiday
    end
  end
end

app/models/active_user.rb
class ActiveUser < ActiveRecord::Base
end

app/models/holiday.rb
class Holiday < ActiveRecord::Base
  belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :at, presence: true
  scope :to_remind, -> {where("remind = ? AND at < ? ", true , 10.minutes.from_now.utc)}
  scope :to_notify, -> {where(notify: true)}

  def self.send_pending_notifications
    Task.to_remind.find_each do |task|
      task.notify_user("remind")
    end
    Task.to_notify.find_each do |task|
      task.notify_user("notify")
    end
  end

  def notify_user(type)
  	if not (ActiveUser.find_by(user_id: self.user_id).nil?)
  		case type
		when "remind"
			head = "Upcoming Task"
			theme = "info"
			self.toggle!(:remind)
		when "notify"
			head = "New Task"
			theme = "success"
			self.toggle!(:notify)
		end
    url = "/tasks/"+self.id.to_s
		PrivatePub.publish_to ("/messages/" + self.user_id.to_s), :head => head, :theme => theme, :content => self.content, :url => url
	end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tasks
  has_many :holidays
  validates :name, presence: true
  validates :email, presence: true
  has_secure_password

  module RoasterConstant
    DAYS_ARRAY = %w{ sunday monday tuesday wednesday thursday friday saturday }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  before_action :logged_in_user, only: [:available_users]
  before_action :admin_user, only: [:available_users]
  def home
  end
  def available_users
  end
  private 
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  def admin_user
    unless current_user.admin?
      flash[:danger] = "Unauthorized access."
      redirect_to(root_url) 
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user, only: [:show]

  def new
    @task = Task.new
    @users = User.all
  end

  def create
    check = task_params
    check[:at] = Time.parse(check[:at])
    @task = Task.new(check)
    if @task.save
      flash[:success] = "Created Task!"
      @task.notify_user('notify')
      redirect_to(root_url)
    else
      render 'new'
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  

  private
  def task_params
    params.require(:task).permit(:content, :user_id, :at)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  def correct_user
    @user = Task.find(params[:id]).user
    unless current_user?(@user) || current_user.admin?
      flash[:danger] = "Unauthorized access."
      redirect_to(root_url) 
    end
  end

  def admin_user
    unless current_user.admin?
      flash[:danger] = "Unauthorized access."
      redirect_to(root_url)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:tasks,:show,:reminders,:notifications]
  before_action :correct_user, only: [:show]
  before_action :admin_user, only: [:roaster,:update_roaster,:index,:get_available_users]
  
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks.order(:at)
  end

  def roaster
    @user = User.find(params[:id])
  end

  def update_roaster
    @user = User.find(params[:id])
    @user.mand_off = roaster_params[:mand_off]
    @user.save!
    redirect_to @user
  end

  def tasks
    render :json => current_user.tasks
  end

  def holiday
    @user = User.find(params[:id])
  end

  def create_holiday
    @user = User.find(params[:id])
    @user.holidays.create(holiday_params)
    redirect_to @user
  end

  def get_available_users
    @date = Date.parse(params[:date])
    week_day = @date.cwday % 7
    @users  = User.where.not(mand_off: week_day).select { |e| 
      if(e.holidays.count != 0)
        e.holidays.where(at: @date).count == 0 
      else
        true
      end
    }
  end




  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  def roaster_params
    params.require(:roaster).permit(:mand_off)
  end

  def holiday_params
    params.require(:holiday).permit(:at)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    unless current_user?(@user) || current_user.admin?
      flash[:danger] = "Unauthorized access."
      redirect_to(root_url) 
    end
  end

  def admin_user
    unless current_user.admin?
      flash[:danger] = "Unauthorized access."
      redirect_to(root_url) 
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user?(user)
    user == current_user
  end

  def admin?
    @current_user.admin
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crm2</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<%= root_url %>">Matsumoto</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <% if logged_in? %>
                    <li><%= link_to "My Profile",current_user %></li>
                    <% if current_user.admin? %>
                        <li><%= link_to "Create Task", new_task_path %></li>
                        <li><%= link_to "All Users", users_path %></li>
                        <li><%= link_to "Available Users", au_handle_path %></li>
                    <% end %>
                <% else %>
                    <li><%= link_to "Login",login_path %></li>
                    <li><%= link_to "Sign up",signup_path %></li>
                <% end %>
            </ul>
            <% if logged_in? %>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Options <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "Logout",logout_path %></li>
                        </ul>
                    </li>
                </ul>
            <% end %>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
</div>
<%= javascript_include_tag 'application' %>
<% if logged_in?%>
    <%= subscribe_to '/messages/' + @current_user.id.to_s %>

    <script type="text/javascript">
        window.user_id = <%= @current_user.id %>;
    </script>
<% end%>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count, "error") %>.
        </div>
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/tasks/new.html.erb
<% provide(:title, 'Create a Task') %>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1>Create task</h1>
        <%= form_for(@task) do |f| %>
            <%= f.label :content %>
            <%= f.text_area :content, class: 'form-control' %>

            <%= f.label :user_id %>
            <%= f.select :user_id, @users.collect { |e| [e[:name], e[:id]] }, {}, {class: 'form-control'} %>

            <%= f.label :at %>
            <%= f.text_field :at, class: 'form-control' %>

            <%= f.submit "Create task", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/tasks/show.html.erb
<% provide(:title, 'Task') %>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <p><strong>Task Details:</strong> <%= @task.content %></p>
        <p><strong>Assigned User:</strong> <%= @task.user.name %></p>
        <p><strong>Scheduled At:</strong> <%= @task.at.localtime.strftime("%F %H:%M") %></p>
    </div>
</div>

app/views/users/get_available_users.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
		<h1>Available users on <%= @date %></h1>
		<ul class="users">
		  <% @users.each do |user| %>
		    <li>
		      <%= link_to user.name, user %>
		    </li>
		  <% end %>
		</ul>
	</div>
</div>

app/views/users/holiday.html.erb
<% provide(:title, "Create Holiday") %>
<h1>Create a holiday for <%= @user.name  %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:holiday, url: create_holiday_user_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :at %>
      <%= f.text_field :at, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages' %>
            <%= f.label :name %>
            <%= f.text_field :name ,class: 'form-control' %>

            <%= f.label :email %>
            <%= f.email_field :email ,class: 'form-control' %>

            <%= f.label :password %>
            <%= f.password_field :password ,class: 'form-control' %>

            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation ,class: 'form-control' %>

            <%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/roaster.html.erb
<% provide(:title, "Edit roaster") %>
<h1>Update Roaster for <%= @user.name  %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:roaster, url: update_roaster_user_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :mand_off %>
      <%= f.select :mand_off,  options_for_select(User::RoasterConstant::DAYS_ARRAY.each_with_index.map { |x,i| [x, i] },@user.mand_off) , {} , {class: 'form-control'} %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-md-3">
		<h3><%= @user.name %></h3>
		<p><%= @user.email %></p>
		<br/>
		<br/>
		<h4>Mandatory Off</h4>
		<p><%= User::RoasterConstant::DAYS_ARRAY[@user.mand_off] %>
		<% if current_user.admin? %>
			<%= link_to "change", roaster_user_path, class: "btn btn-warning btn-xs" %>
		<% end %></p>
		<br/>
		<br/>
		<h4>Leaves taken</h4>
		<% @user.holidays.each do |e| %>
			<p><%= e.at %></p>
		<% end %>
		<% if current_user.admin? %>
			<%= link_to "add leave", holiday_user_path, class: "btn btn-warning btn-xs" %>
		<% end %>
	</div>
	<div class="col-md-9">
		<h2>Your Tasks</h2>
		<% @tasks.each do |e| %>
			<div class="row">
				<div class="col-md-12">
					<h4><%= link_to e.content, e %></h4>
					<p>Scheduled at : <%= e.at.localtime.strftime("%F %H:%M") %></p>
					<p>Created at: <%= e.created_at.localtime.strftime("%F %H:%M") %> </p>
				</div>
			</div>
		<% end %>
	</div>
</div>